

---
#https://cloud.spring.io/spring-cloud-gateway/reference/html/
spring:
  profiles: local
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9100
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*),/$\{path}
        - id: order-service
          uri: http://localhost:9200
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


---
spring:
  profiles: dev

---
spring:
  profiles: prod