

---
spring:
  profiles: local

api:
  order:
    port: 9200
    url: http://localhost:${api.order.port}

---
spring:
  profiles: dev

api:
  order:
    port: 9200
    url: http://msa-dev-order:${api.order.port}

---
spring:
  profiles: prod

api:
  order:
    port: 9200
    url: http://msa-prod-order:${api.order.port}